on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: dev.elixir-europe.org
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/public_html/grav/**
            **/public_html/kirby/**
            **/public_html/b1mg/**
            **/public_html/rdmtoolkit-home/**
            **/public_html/fairplus/**
            **/public_html/old/**